# `numpy`

In [1]:
import numpy as np

In [2]:
a = np.random.random((2,2))

In [3]:
a

array([[0.36979488, 0.42214251],
       [0.83133107, 0.44094714]])

In [6]:
a[1,1] #rows first, then columns
# in general case: we follow the axis of the shape

0.44094713887748005

In [7]:
a.shape

(2, 2)

In [8]:
b = np.random.random((4,3,2))

In [11]:
b

array([[[0.02956304, 0.35333452],
        [0.00545667, 0.58508611],
        [0.51718027, 0.77798816]],

       [[0.28712612, 0.90012918],
        [0.07528247, 0.94749792],
        [0.02130239, 0.36511644]],

       [[0.76135466, 0.74548947],
        [0.12514933, 0.153094  ],
        [0.41498997, 0.22106728]],

       [[0.28767102, 0.87516298],
        [0.9153372 , 0.47920259],
        [0.10088765, 0.10784138]]])

In [10]:
b[1, 2, 0]

0.0213023910314738

In [13]:
b.T.shape

(2, 3, 4)

In [14]:
b.transpose()

array([[[0.02956304, 0.28712612, 0.76135466, 0.28767102],
        [0.00545667, 0.07528247, 0.12514933, 0.9153372 ],
        [0.51718027, 0.02130239, 0.41498997, 0.10088765]],

       [[0.35333452, 0.90012918, 0.74548947, 0.87516298],
        [0.58508611, 0.94749792, 0.153094  , 0.47920259],
        [0.77798816, 0.36511644, 0.22106728, 0.10784138]]])

In [15]:
b

array([[[0.02956304, 0.35333452],
        [0.00545667, 0.58508611],
        [0.51718027, 0.77798816]],

       [[0.28712612, 0.90012918],
        [0.07528247, 0.94749792],
        [0.02130239, 0.36511644]],

       [[0.76135466, 0.74548947],
        [0.12514933, 0.153094  ],
        [0.41498997, 0.22106728]],

       [[0.28767102, 0.87516298],
        [0.9153372 , 0.47920259],
        [0.10088765, 0.10784138]]])

In [16]:
b[2:]

array([[[0.76135466, 0.74548947],
        [0.12514933, 0.153094  ],
        [0.41498997, 0.22106728]],

       [[0.28767102, 0.87516298],
        [0.9153372 , 0.47920259],
        [0.10088765, 0.10784138]]])

In [17]:
b[2:, :, 0] #the last two matrices, all the rows, first column

array([[0.76135466, 0.12514933, 0.41498997],
       [0.28767102, 0.9153372 , 0.10088765]])

In [18]:
b.sum()

10.052310818745013

In [21]:
a

array([[0.36979488, 0.42214251],
       [0.83133107, 0.44094714]])

In [22]:
a.sum()

2.0642155989759923

In [23]:
a.sum(axis=0)

array([1.20112595, 0.86308965])

In [24]:
a.sum(axis=1)

array([0.79193739, 1.27227821])

In [25]:
b

array([[[0.02956304, 0.35333452],
        [0.00545667, 0.58508611],
        [0.51718027, 0.77798816]],

       [[0.28712612, 0.90012918],
        [0.07528247, 0.94749792],
        [0.02130239, 0.36511644]],

       [[0.76135466, 0.74548947],
        [0.12514933, 0.153094  ],
        [0.41498997, 0.22106728]],

       [[0.28767102, 0.87516298],
        [0.9153372 , 0.47920259],
        [0.10088765, 0.10784138]]])

In [26]:
b.sum(axis=0)

array([[1.36571484, 2.87411615],
       [1.12122567, 2.16488061],
       [1.05436028, 1.47201326]])

In [27]:
b.sum(axis=1)

array([[0.55219998, 1.71640879],
       [0.38371098, 2.21274354],
       [1.30149396, 1.11965075],
       [1.30389586, 1.46220695]])

In [28]:
b.sum(axis=2)

array([[0.38289756, 0.59054277, 1.29516843],
       [1.1872553 , 1.0227804 , 0.38641883],
       [1.50684413, 0.27824333, 0.63605726],
       [1.162834  , 1.39453978, 0.20872902]])

In [29]:
b.sort()

In [36]:
c = np.arange(16,0,-1).reshape((2,2,2,2))

In [37]:
c

array([[[[16, 15],
         [14, 13]],

        [[12, 11],
         [10,  9]]],


       [[[ 8,  7],
         [ 6,  5]],

        [[ 4,  3],
         [ 2,  1]]]])

In [38]:
c.sort()

In [39]:
c

array([[[[15, 16],
         [13, 14]],

        [[11, 12],
         [ 9, 10]]],


       [[[ 7,  8],
         [ 5,  6]],

        [[ 3,  4],
         [ 1,  2]]]])

In [40]:
c.sort(axis=0)
c

array([[[[ 7,  8],
         [ 5,  6]],

        [[ 3,  4],
         [ 1,  2]]],


       [[[15, 16],
         [13, 14]],

        [[11, 12],
         [ 9, 10]]]])

In [41]:
c.sort(axis=1)
c

array([[[[ 3,  4],
         [ 1,  2]],

        [[ 7,  8],
         [ 5,  6]]],


       [[[11, 12],
         [ 9, 10]],

        [[15, 16],
         [13, 14]]]])

In [42]:
c.sort(axis=2)
c

array([[[[ 1,  2],
         [ 3,  4]],

        [[ 5,  6],
         [ 7,  8]]],


       [[[ 9, 10],
         [11, 12]],

        [[13, 14],
         [15, 16]]]])

In [49]:
(c+2)/6

array([[[[0.5       , 0.66666667],
         [0.83333333, 1.        ]],

        [[1.16666667, 1.33333333],
         [1.5       , 1.66666667]]],


       [[[1.83333333, 2.        ],
         [2.16666667, 2.33333333]],

        [[2.5       , 2.66666667],
         [2.83333333, 3.        ]]]])

# lab review

In [50]:
import numpy as np
np.__version__

'1.19.2'

In [51]:
a = np.random.random((2,3,5))

In [52]:
a

array([[[0.253989  , 0.32009465, 0.50451828, 0.85598937, 0.49596128],
        [0.49677849, 0.09792105, 0.12356294, 0.28100325, 0.39739346],
        [0.20988877, 0.78162371, 0.99727323, 0.4603195 , 0.31087611]],

       [[0.25332667, 0.90318871, 0.58070665, 0.19131253, 0.97380128],
        [0.35609198, 0.76681598, 0.35778851, 0.01993495, 0.85360749],
        [0.13376835, 0.28773623, 0.89012556, 0.35337519, 0.40974477]]])

In [53]:
b = np.ones((5,2,3))
b

array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

In [54]:
a.size == b.size

True

In [55]:
a+b

ValueError: operands could not be broadcast together with shapes (2,3,5) (5,2,3) 

In [56]:
c = b.transpose((1,2,0))

In [58]:
b.shape

(5, 2, 3)

In [61]:
b.transpose((1,0,2)).shape

(2, 5, 3)

In [65]:
d = a+c

In [66]:
e = a*c

In [68]:
e==a

array([[[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]],

       [[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]]])

In [69]:
d_max = d.max()
d_min = d.min()
d_mean = d.mean()

In [70]:
f = np.empty((2,3,5))

In [71]:
f

array([[[0.253989  , 0.32009465, 0.50451828, 0.85598937, 0.49596128],
        [0.49677849, 0.09792105, 0.12356294, 0.28100325, 0.39739346],
        [0.20988877, 0.78162371, 0.99727323, 0.4603195 , 0.31087611]],

       [[0.25332667, 0.90318871, 0.58070665, 0.19131253, 0.97380128],
        [0.35609198, 0.76681598, 0.35778851, 0.01993495, 0.85360749],
        [0.13376835, 0.28773623, 0.89012556, 0.35337519, 0.40974477]]])

In [72]:
for idx1, m_1 in enumerate(d):
    for idx2, m_2 in enumerate(m_1):
        for idx, i in enumerate(m_2):
            if d_min < i < d_mean:
                f[idx1, idx2, idx] = 25
            elif d_mean < i < d_max:
                f[idx1, idx2, idx] = 75
            elif i == d_mean:
                f[idx1, idx2, idx] = 50
            elif i == d_min:
                f[idx1, idx2, idx] = 0
            elif i == d_max:
                f[idx1, idx2, idx] = 100

In [73]:
f

array([[[ 25.,  25.,  75.,  75.,  75.],
        [ 75.,  25.,  25.,  25.,  25.],
        [ 25.,  75., 100.,  25.,  25.]],

       [[ 25.,  75.,  75.,  25.,  75.],
        [ 25.,  75.,  25.,   0.,  75.],
        [ 25.,  25.,  75.,  25.,  25.]]])

In [74]:
f=np.where(d==d_max,100,d)
f=np.where(d<d_max, 75, f)
f=np.where(d==d_mean, 50, f)
f=np.where(d<d_mean, 25, f)
f=np.where(d==d_min, 0, f)

In [75]:
f

array([[[ 25.,  25.,  75.,  75.,  75.],
        [ 75.,  25.,  25.,  25.,  25.],
        [ 25.,  75., 100.,  25.,  25.]],

       [[ 25.,  75.,  75.,  25.,  75.],
        [ 25.,  75.,  25.,   0.,  75.],
        [ 25.,  25.,  75.,  25.,  25.]]])

In [76]:
g=np.where(f==100,'E',f)
g=np.where(f==75, 'D', g)
g=np.where(f==50, 'C', g)
g=np.where(f==25, 'B', g)
g=np.where(f==0, 'A', g)

In [77]:
g

array([[['B', 'B', 'D', 'D', 'D'],
        ['D', 'B', 'B', 'B', 'B'],
        ['B', 'D', 'E', 'B', 'B']],

       [['B', 'D', 'D', 'B', 'D'],
        ['B', 'D', 'B', 'A', 'D'],
        ['B', 'B', 'D', 'B', 'B']]], dtype='<U32')

# `map`

In [85]:
def foo(x):
    return x%2==0

In [86]:
foo(3)

False

In [87]:
lst = [10,11,13,47,22]

In [88]:
[foo(i) for i in lst]

[True, False, False, False, True]

In [89]:
list(map(foo, lst))

[True, False, False, False, True]

# `filter`

In [91]:
list(filter(foo, lst))

[10, 22]

# `reduce`

<img src = 'https://www.python-course.eu/images/reduce_diagram.png'>

In [92]:
lst = [47,11,42,13]
def func(a,b):
    return a+b

In [94]:
from functools import reduce

In [95]:
reduce(func, lst)

113

a   | b  | a+b  
47  | 11 | 58  
58  | 42 | 100  
100 | 13 | 113  

In [97]:
def func(a,b):
    return a if a>b else b

In [98]:
reduce(func,lst)

47

# `lambda`

```python
lambda args: expression
```

In [99]:
def squared(x):
    return x**2

In [100]:
def squared(x): return x**2

In [102]:
map(def foo(x): return x**2, lst)

SyntaxError: invalid syntax (<ipython-input-102-826519a909e2>, line 1)

In [103]:
lambda x: x**2

<function __main__.<lambda>(x)>

In [105]:
list(map(lambda x: x**2, lst))

[2209, 121, 1764, 169]

In [106]:
foo = lambda x: x**2

In [109]:
foo(10)

100

In [110]:
def foo(x,y):
    return x/y if y!=0 else 0

In [112]:
foo(1,0)

0

In [114]:
div = lambda x,y: x/y if y!=0 else 0

In [115]:
div(1,2)

0.5

In [116]:
(lambda x,y: x/y if y!=0 else 0)(1,2)

0.5

In [120]:
range(5,11)

range(5, 11)

In [121]:
def generate_range(lower):
    return lambda upper: range(lower, upper)

In [124]:
range10 = generate_range(10)

In [126]:
range10(20)

range(10, 20)

In [127]:
list_of_topics = ['python-programming','mysql','web-scraping','pandas','tableau','data-viz','stats','machine-learning']

In [128]:
list_of_topics

['python-programming',
 'mysql',
 'web-scraping',
 'pandas',
 'tableau',
 'data-viz',
 'stats',
 'machine-learning']

In [130]:
[i.replace('-',' ').title() for i in list_of_topics]

['Python Programming',
 'Mysql',
 'Web Scraping',
 'Pandas',
 'Tableau',
 'Data Viz',
 'Stats',
 'Machine Learning']

In [131]:
list(map(lambda x: x.replace('-',' ').title(), list_of_topics))

['Python Programming',
 'Mysql',
 'Web Scraping',
 'Pandas',
 'Tableau',
 'Data Viz',
 'Stats',
 'Machine Learning']

In [133]:
dct_of_topics = {x:len(x) for x in list_of_topics}

In [146]:
dict(sorted(dct_of_topics.items(), key = lambda x:x[1]))

{'mysql': 5,
 'stats': 5,
 'pandas': 6,
 'tableau': 7,
 'data-viz': 8,
 'web-scraping': 12,
 'machine-learning': 16,
 'python-programming': 18}

# pandas `map, apply, applymap`

In [148]:
import pandas as pd

In [150]:
df = pd.DataFrame([[1,2,3],[2,3,np.nan]])

In [151]:
df

0  1    2
0  1  2  3.0
1  2  3  NaN

Divide the column 0 by 2

In [152]:
df[0]/2

0    0.5
1    1.0
Name: 0, dtype: float64

Divide the column 0 by 2 if the value is even, else - multiply by 3

In [153]:
def foo(x):
    return x/2 if x%2==0 else x*3

In [154]:
df[0].map(foo)

0    3.0
1    1.0
Name: 0, dtype: float64

In [155]:
df[0].apply(foo) # no difference with map at this stage

0    3.0
1    1.0
Name: 0, dtype: float64

In [156]:
df[0].applymap(foo) #applymap can only be used for DataFrames

AttributeError: 'Series' object has no attribute 'applymap'

In [158]:
df.map(foo) # map only exists for Series

AttributeError: 'DataFrame' object has no attribute 'map'

In [159]:
df.apply(foo) # tries to apply the function to every element of df, which are Series. So x - Serie. 
# since we can't say Series%2==0, it crushes

ValueError: The truth value of a Series is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().

In [160]:
df.applymap(foo) # applies the function to every single value of the DataFrame (each cell)

0    1    2
0  3.0  1.0  9.0
1  1.0  9.0  NaN

* map - works only for Series. Applies the function to cells  
* applymap - works only for DataFrames. Applies the function to cells  
* apply - works both for Series and DataFrames, but has a different application for the two:
    - Series: almost the same as map for series. Applies the function to cells
    - DataFrames: applies function to the Series of df. [Note: can work both for rows and columns]

In [161]:
dct = {1:'apple', 2:'plum'}

In [164]:
df[0].map(dct)

0    apple
1     plum
Name: 0, dtype: object

In [167]:
df[0].map(dct)

0    apple
1     plum
Name: 0, dtype: object

In [168]:
df[1].map(dct)

0    plum
1     NaN
Name: 1, dtype: object

In [169]:
df[2].map(dct)

0    NaN
1    NaN
Name: 2, dtype: object

In [170]:
df=pd.read_csv('https://ironhack.school/asset-v1:IRONHACK+DAFT+201910_PAR+type@asset+block@IMDB-Movie-Data.csv')

In [173]:
df.head()

Rank                    Title                     Genre  \
0     1  Guardians of the Galaxy   Action,Adventure,Sci-Fi   
1     2               Prometheus  Adventure,Mystery,Sci-Fi   
2     3                    Split           Horror,Thriller   
3     4                     Sing   Animation,Comedy,Family   
4     5            Suicide Squad  Action,Adventure,Fantasy   

                                         Description              Director  \
0  A group of intergalactic criminals are forced ...            James Gunn   
1  Following clues to the origin of mankind, a te...          Ridley Scott   
2  Three girls are kidnapped by a man with a diag...    M. Night Shyamalan   
3  In a city of humanoid animals, a hustling thea...  Christophe Lourdelet   
4  A secret government agency recruits some of th...            David Ayer   

                                              Actors  Year  Runtime (Minutes)  \
0  Chris Pratt, Vin Diesel, Bradley Cooper, Zoe S...  2014                121   
1  Noomi Rapace, Logan Marshall-Green, Michael Fa...  2012                124   
2  James McAvoy, Anya Taylor-Joy, Haley Lu Richar...  2016                117   
3  Matthew McConaughey,Reese Witherspoon, Seth Ma...  2016                108   
4  Will Smith, Jared Leto, Margot Robbie, Viola D...  2016                123   

   Rating   Votes  Revenue (Millions)  Metascore  
0     8.1  757074              333.13       76.0  
1     7.0  485820              126.46       65.0  
2     7.3  157606              138.12       62.0  
3     7.2   60545              270.32       59.0  
4     6.2  393727              325.02       40.0

In [179]:
(df.Metascore/10 + df.Rating)/2

0      7.85
1      6.75
2      6.75
3      6.55
4      5.10
       ... 
995    5.35
996    5.05
997    5.60
998    3.90
999    3.20
Length: 1000, dtype: float64

In [182]:
df.apply(lambda x: (x.Rating+x.Metascore/10)/2 , axis = 1)

0      7.85
1      6.75
2      6.75
3      6.55
4      5.10
       ... 
995    5.35
996    5.05
997    5.60
998    3.90
999    3.20
Length: 1000, dtype: float64

dtype('O')

In [187]:
def range_num(x: pd.Series):
    if isinstance(x[0], str): return 'N/A'
    else: return x.max()-x.min()

In [192]:
range_num(df.Year)

10

In [188]:
df.apply(range_num)

Rank                      999
Title                     N/A
Genre                     N/A
Description               N/A
Director                  N/A
Actors                    N/A
Year                       10
Runtime (Minutes)         125
Rating                    7.1
Votes                 1791855
Revenue (Millions)     936.63
Metascore                89.0
dtype: object

Select action movies

In [198]:
df.loc[df.Genre.str.contains('Action')].head()

Rank                    Title                       Genre  \
0      1  Guardians of the Galaxy     Action,Adventure,Sci-Fi   
4      5            Suicide Squad    Action,Adventure,Fantasy   
5      6           The Great Wall    Action,Adventure,Fantasy   
8      9       The Lost City of Z  Action,Adventure,Biography   
12    13                Rogue One     Action,Adventure,Sci-Fi   

                                          Description        Director  \
0   A group of intergalactic criminals are forced ...      James Gunn   
4   A secret government agency recruits some of th...      David Ayer   
5   European mercenaries searching for black powde...     Yimou Zhang   
8   A true-life drama, centering on British explor...      James Gray   
12  The Rebel Alliance makes a risky move to steal...  Gareth Edwards   

                                               Actors  Year  \
0   Chris Pratt, Vin Diesel, Bradley Cooper, Zoe S...  2014   
4   Will Smith, Jared Leto, Margot Robbie, Viola D...  2016   
5       Matt Damon, Tian Jing, Willem Dafoe, Andy Lau  2016   
8   Charlie Hunnam, Robert Pattinson, Sienna Mille...  2016   
12  Felicity Jones, Diego Luna, Alan Tudyk, Donnie...  2016   

    Runtime (Minutes)  Rating   Votes  Revenue (Millions)  Metascore  
0                 121     8.1  757074              333.13       76.0  
4                 123     6.2  393727              325.02       40.0  
5                 103     6.1   56036               45.13       42.0  
8                 141     7.1    7188                8.01       78.0  
12                133     7.9  323118              532.17       65.0

In [199]:
df.loc[df.Genre =='Action']

Rank                 Title   Genre  \
123   124  Boyka: Undisputed IV  Action   
580   581  Kickboxer: Vengeance  Action   

                                           Description         Director  \
123  In the fourth installment of the fighting fran...  Todor Chapkanov   
580         A kick boxer is out to avenge his brother.   John Stockwell   

                                                Actors  Year  \
123  Scott Adkins, Teodora Duhovnikova, Alon Aboutb...  2016   
580  Dave Bautista, Alain Moussi, Gina Carano, Jean...  2016   

     Runtime (Minutes)  Rating  Votes  Revenue (Millions)  Metascore  
123                 86     7.4  10428                 NaN        NaN  
580                 90     4.9   6809              131.56       37.0

I am quite picky. I want to select only those movies that are 
* just action, 
* thriller action or 
* adventure action.

In [240]:
dummies = df.Genre.str.get_dummies(sep=',')
dummies[(dummies['Action']==1)]

Action  Adventure  Animation  Biography  Comedy  Crime  Drama  Family  \
0         1          1          0          0       0      0      0       0   
4         1          1          0          0       0      0      0       0   
5         1          1          0          0       0      0      0       0   
8         1          1          0          1       0      0      0       0   
12        1          1          0          0       0      0      0       0   
..      ...        ...        ...        ...     ...    ...    ...     ...   
958       1          0          0          0       0      0      1       0   
968       1          0          0          0       0      0      0       0   
969       1          1          0          0       0      0      0       0   
990       1          1          0          0       0      0      0       0   
993       1          1          0          0       0      0      0       0   

     Fantasy  History  Horror  Music  Musical  Mystery  Romance  Sci-Fi  \
0          0        0       0      0        0        0        0       1   
4          1        0       0      0        0        0        0       0   
5          1        0       0      0        0        0        0       0   
8          0        0       0      0        0        0        0       0   
12         0        0       0      0        0        0        0       1   
..       ...      ...     ...    ...      ...      ...      ...     ...   
958        0        0       0      0        0        0        0       0   
968        0        0       1      0        0        0        0       0   
969        0        0       0      0        0        0        0       0   
990        1        0       0      0        0        0        0       0   
993        0        0       1      0        0        0        0       0   

     Sport  Thriller  War  Western  
0        0         0    0        0  
4        0         0    0        0  
5        0         0    0        0  
8        0         0    0        0  
12       0         0    0        0  
..     ...       ...  ...      ...  
958      0         1    0        0  
968      0         1    0        0  
969      0         0    0        1  
990      0         0    0        0  
993      0         0    0        0  

[303 rows x 20 columns]

In [209]:
df[df.Genre =='Thriller,Action']

Empty DataFrame
Columns: [Rank, Title, Genre, Description, Director, Actors, Year, Runtime (Minutes), Rating, Votes, Revenue (Millions), Metascore]
Index: []

In [224]:
df.Genre=='Action'                       #movie is action
df.Genre.str.split(',').map(len)==2      #movie has only 2 genres
df.Genre.str.contains('Action')          #Action is one of the Genres
df.Genre.str.split(',').map(set).map(lambda x: (x-{'Action','Thriller','Adventure'})==set()) #genre combined from action, thriller, adventure

0      False
1      False
2      False
3      False
4      False
       ...  
995    False
996    False
997    False
998    False
999    False
Name: Genre, Length: 1000, dtype: bool

In [238]:
df.loc[
    (df.Genre.str.split(',').map(set).map(lambda x: (x-{'Action','Thriller','Adventure'})==set())) &
    (df.Genre.str.contains('Action')) &
    (df.Genre.str.split(',').map(len)<=2)
].shape

(14, 12)

In [237]:
df[df.Genre.str.split(',').map(set).apply(
    lambda x: ('Action' in x) & (len(x)<=2) & ((x-{'Action','Thriller','Adventure'})==set())
)].shape

(14, 12)

Calculate the average number of words in Description and Actors columns

In [249]:
print(df.Actors.str.split().map(len).mean())
df.Description.str.split().map(len).mean()

7.86


27.921

In [251]:
df[['Description','Actors']].str.split()

AttributeError: 'DataFrame' object has no attribute 'str'

In [256]:
df[['Description','Actors', 'Director']].applymap(lambda x: len(x.split())).mean()

Description    27.921
Actors          7.860
Director        2.092
dtype: float64