# Intrduction to NumPy


#### 1. Importer NumPy sous le nom np.

In [1]:
# your code here
import numpy as np

#### 2. Printer votre version NumPy.

In [19]:
# your code here
import numpy

print(numpy.__version__)

1.26.4


#### 3. Generer un 2x3x5 3-dimensional array avec des valeurs random. Assigner la array à la variable *a*.
**Challenge**: il y a au moins 3  façons faciles qui utilisent  numpy pour generer un random array. 

In [4]:
# Method 1
# np.random.rand() → valeurs entre 0 et 1
a = np.random.rand(2, 3, 5)
print("Méthode 1 :")
print(a)



Méthode 1 :
[[[0.48268207 0.82353238 0.4731841  0.39493256 0.70952674]
  [0.84810651 0.77179187 0.46484256 0.48105532 0.51021647]
  [0.14355771 0.65747781 0.98618814 0.19942232 0.93314613]]

 [[0.26178408 0.57163859 0.23217745 0.06919899 0.72625715]
  [0.19028162 0.7975753  0.20208885 0.1017864  0.30585232]
  [0.63191459 0.53498385 0.05793253 0.50114061 0.4539402 ]]]


In [5]:
# Method 2
# np.random.random_sample() → valeurs entre 0 et 1
a = np.random.random_sample((2, 3, 5))
print("\nMéthode 2 :")
print(a)




Méthode 2 :
[[[0.84196137 0.28556476 0.7774285  0.77690346 0.44542655]
  [0.7393188  0.45089145 0.46670259 0.10678566 0.01341549]
  [0.36438527 0.421883   0.29991338 0.27054326 0.01013472]]

 [[0.76176074 0.16435105 0.26675307 0.45319939 0.53663583]
  [0.37980907 0.3703094  0.16247344 0.97198807 0.19104212]
  [0.17492156 0.72251605 0.66929794 0.19706979 0.70929204]]]


In [ ]:
# Method 3
#np.random.randn() → distribution normale centrée réduite
a = np.random.randn(2, 3, 5)
print("\nMéthode 3 :")
print(a)


Méthode 3 :
[[[-1.08493191  0.09629059  0.1111833  -0.51728653  1.16722752]
  [ 1.30095783  0.16363031 -2.26650046 -1.13933565 -1.39848096]
  [ 0.6884317  -1.50372184 -0.12786624  0.42883458 -0.57089908]]

 [[ 0.2403095   0.25096501 -0.72754693 -0.20707372 -1.57197083]
  [ 0.64616294  0.91730631  1.76482583 -0.76083828  0.02753178]
  [-0.01835472 -0.55504357  0.11250378  0.08986002 -0.20948842]]]


#### 4. Print *a*.


In [21]:
# your code here
print(a)

[[[0.02384183 0.89311927 0.12321854 0.21679543 0.0067157 ]
  [0.26016623 0.80977447 0.76360333 0.88528874 0.24175605]
  [0.46112242 0.08604115 0.51481299 0.27866964 0.61674643]]

 [[0.4341355  0.56432659 0.34080839 0.42401045 0.42666898]
  [0.38297597 0.09210511 0.07322965 0.25382633 0.88322828]
  [0.19213064 0.73205576 0.53690295 0.05417198 0.04478365]]]


#### 5. Créer un 5x2x3 3-dimensional array avec toutes les valeurs égales à 1. Assignez le array à la variable *b*.

In [10]:
# your code here
b = np.ones((5, 2, 3))


#### 6. Print *b*.


In [9]:
# your code here

print(b)

[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]


#### 7. Est ce que *a* et *b* ont la même size? Comment le prouvez avec un code Python ?

In [11]:
# your code here
import numpy as np

# Exemple : a et b comme précédemment
a = np.random.rand(2, 3, 5)
b = np.ones((5, 2, 3))

# Vérifier la shape
print("Shape de a :", a.shape)
print("Shape de b :", b.shape)

# Vérifier la taille totale
print("Size de a :", a.size)
print("Size de b :", b.size)

# Vérifier s'ils ont la même taille
print("Même taille ? :", a.size == b.size)


Shape de a : (2, 3, 5)
Shape de b : (5, 2, 3)
Size de a : 30
Size de b : 30
Même taille ? : True


#### 8. Est il possible d'additionner *a* and *b*? PQ ou PQ pas?


In [ ]:
# your answer here
a+b

#En NumPy, l’addition (a + b) fonctionne élément par élément, si et seulement si :

# Les arrays ont la même forme
# OU

# Ils sont broadcastables l’un vers l’autre

ValueError: operands could not be broadcast together with shapes (2,3,5) (5,2,3) 

In [13]:
#Reshape :
# restructurer b pour qu’il ait la même shape que a :


b2 = b.reshape(2, 3, 5)
resultat = a + b2
# Transpose :
# réorganiser les axes de b pour le rendre compatible :


b2 = b.transpose(1, 2, 0)  # Exemple
print(b2.shape)  # Vérifier si ça colle

(2, 3, 5)


#### 9. Transposez *b* de telle sorte qu'il ait la même structure que *a* (i.e. devient un 2x3x5 array). Assignez le array transposé à la variable *c*.

In [20]:
# your code here


# Exemple pour rappel
b = np.ones((5, 2, 3))

# Transposer les axes : de (5, 2, 3) --> (2, 3, 5)
c = b.transpose(1, 2, 0)

print("Shape de b :", b.shape)
print("Shape de c :", c.shape)


#b.transpose(1, 2, 0) :

# 1 → premier axe devient le deuxième (2)

# 2 → deuxième axe devient le troisième (3)

# 0 → dernier axe devient le premier (5 → replacé à la fin)


Shape de b : (5, 2, 3)
Shape de c : (2, 3, 5)


#### 10. Essayez d'additionner *a* & *c*. Mnt ça devrait marcher. Assignez la somme (sum) à la variable *d*. Mais PQ ça marche maintenant?

In [22]:
# your code/answer here

import numpy as np

# # Exemple : a et b comme avant
# a = np.random.rand(2, 3, 5)
# b = np.ones((5, 2, 3))

# # Transposer b pour obtenir c
# c = b.transpose(1, 2, 0)

# Additionner a et c
d = a + c

print("Shape de a :", a.shape)
print("Shape de c :", c.shape)
print("Shape de d :", d.shape)
print("\nExemple de somme :", d)


Shape de a : (2, 3, 5)
Shape de c : (2, 3, 5)
Shape de d : (2, 3, 5)

Exemple de somme : [[[1.02384183 1.89311927 1.12321854 1.21679543 1.0067157 ]
  [1.26016623 1.80977447 1.76360333 1.88528874 1.24175605]
  [1.46112242 1.08604115 1.51481299 1.27866964 1.61674643]]

 [[1.4341355  1.56432659 1.34080839 1.42401045 1.42666898]
  [1.38297597 1.09210511 1.07322965 1.25382633 1.88322828]
  [1.19213064 1.73205576 1.53690295 1.05417198 1.04478365]]]


#### 11. Printez *a* and *d*. Remarquez la différence et la relation entre les deux arrays en termes de valeurs? Expliquez.

In [23]:
# your code/answer here
import numpy as np

# a (valeurs aléatoires)
a = np.random.rand(2, 3, 5)

#  b rempli de 1, puis le transposer
b = np.ones((5, 2, 3))
c = b.transpose(1, 2, 0)

# Somme
d = a + c

# Afficher a et d
print("a =\n", a)
print("\nd =\n", d)


a =
 [[[0.90506035 0.74456192 0.52437791 0.05909387 0.22316464]
  [0.94208551 0.84805785 0.23636664 0.06782013 0.00269329]
  [0.89234944 0.62832602 0.29106142 0.41405741 0.92001142]]

 [[0.93708009 0.51376295 0.31249466 0.13987897 0.8813758 ]
  [0.54359205 0.96767765 0.20203487 0.59076269 0.83757736]
  [0.09552003 0.06461275 0.9633701  0.86389538 0.04121499]]]

d =
 [[[1.90506035 1.74456192 1.52437791 1.05909387 1.22316464]
  [1.94208551 1.84805785 1.23636664 1.06782013 1.00269329]
  [1.89234944 1.62832602 1.29106142 1.41405741 1.92001142]]

 [[1.93708009 1.51376295 1.31249466 1.13987897 1.8813758 ]
  [1.54359205 1.96767765 1.20203487 1.59076269 1.83757736]
  [1.09552003 1.06461275 1.9633701  1.86389538 1.04121499]]]


#### 12. Multipliez *a* et *c*. Assignez le résultats à *e*.

In [25]:
# your code here
# Multiplication élément par élément
e = a * c
print(a)
print(c)
print(e)

[[[0.90506035 0.74456192 0.52437791 0.05909387 0.22316464]
  [0.94208551 0.84805785 0.23636664 0.06782013 0.00269329]
  [0.89234944 0.62832602 0.29106142 0.41405741 0.92001142]]

 [[0.93708009 0.51376295 0.31249466 0.13987897 0.8813758 ]
  [0.54359205 0.96767765 0.20203487 0.59076269 0.83757736]
  [0.09552003 0.06461275 0.9633701  0.86389538 0.04121499]]]
[[[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]]
[[[0.90506035 0.74456192 0.52437791 0.05909387 0.22316464]
  [0.94208551 0.84805785 0.23636664 0.06782013 0.00269329]
  [0.89234944 0.62832602 0.29106142 0.41405741 0.92001142]]

 [[0.93708009 0.51376295 0.31249466 0.13987897 0.8813758 ]
  [0.54359205 0.96767765 0.20203487 0.59076269 0.83757736]
  [0.09552003 0.06461275 0.9633701  0.86389538 0.04121499]]]


#### 13. Est ce que *e* égales à *a*? PQ ou PQ pas ?


In [26]:
# your code/answer here
import numpy as np

# Vérification : e et a sont-ils identiques ?
print(np.array_equal(e, a))  # True


True


#### 14. Identifiez le max, min, et la valeurs moyenne e, *d*. Assignez ces valeurs à la  variables *d_max*, *d_min* and *d_mean*.

In [27]:
# your code here
# Calculer max, min et moyenne
d_max = d.max()
d_min = d.min()
d_mean = d.mean()

print("d_max :", d_max)
print("d_min :", d_min)
print("d_mean :", d_mean)

d_max : 1.967677647846433
d_min : 1.0026932868846774
d_mean : 1.5217979393047512


#### 15. Maintenant on veut labelliser les valeurs en *d*. Premièrement, créez un array vide *f* avec la même shape (i.e. 2x3x5) que *d* utilisez `np.empty`.


In [28]:
# your code here
import numpy as np


# Créer un tableau vide f avec la même shape que d
f = np.empty(d.shape)

print("Shape de d :", d.shape)
print("Shape de f :", f.shape)
print("f =\n", f)


Shape de d : (2, 3, 5)
Shape de f : (2, 3, 5)
f =
 [[[0.90506035 0.74456192 0.52437791 0.05909387 0.22316464]
  [0.94208551 0.84805785 0.23636664 0.06782013 0.00269329]
  [0.89234944 0.62832602 0.29106142 0.41405741 0.92001142]]

 [[0.93708009 0.51376295 0.31249466 0.13987897 0.8813758 ]
  [0.54359205 0.96767765 0.20203487 0.59076269 0.83757736]
  [0.09552003 0.06461275 0.9633701  0.86389538 0.04121499]]]


#### 16. Remplissez les valeurs dans *f*.

Pour chaque valeur dans *d* :  
- Si elle est supérieure à *d_min* mais inférieure à *d_mean*, attribuez 25 à la valeur correspondante dans *f*.  
- Si une valeur dans *d* est supérieure à *d_mean* mais inférieure à *d_max*, attribuez 75 à la valeur correspondante dans *f*.  
- Si une valeur est égale à *d_mean*, attribuez 50 à la valeur correspondante dans *f*.  
- Attribuez 0 à la (ou aux) valeur(s) correspondante(s) dans *f* pour *d_min* dans *d*.  
- Attribuez 100 à la (ou aux) valeur(s) correspondante(s) dans *f* pour *d_max* dans *d*.

À la fin, *f* ne doit contenir que les valeurs suivantes : 0, 25, 50, 75 et 100.

**Remarque** : vous n’êtes pas obligé d’utiliser Numpy pour cette question.


In [1]:
# your code here

#### 17. Printez *d* et *f*. Avez vous obtenu ce que vous expectiez expected *f*?
Par exemple, if your *d* is:
```python
[[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
[1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
[1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],
[[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
[1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
[1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]]
```
Your *f* should be:
```python
[[[ 75.,  75.,  75.,  25.,  75.],
[ 75.,  75.,  25.,  25.,  25.],
[ 75.,  25.,  75.,  75.,  75.]],
[[ 25.,  25.,  25.,  25., 100.],
[ 75.,  75.,  75.,  75.,  75.],
[ 25.,  75.,   0.,  75.,  75.]]]
```

In [ ]:
# your code here

#### 18. Question bonus : au lieu d’utiliser des nombres (c’est-à-dire 0, 25, 50, 75 et 100), utilisez des valeurs sous forme de chaînes de caractères ("A", "B", "C", "D" et "E") pour étiqueter les éléments du tableau. Pour l’exemple ci-dessus, le résultat attendu est :


```python
[[[ 'D',  'D',  'D',  'B',  'D'],
[ 'D',  'D',  'B',  'B',  'B'],
[ 'D',  'B',  'D',  'D',  'D']],
[[ 'B',  'B',  'B',  'B',  'E'],
[ 'D',  'D',  'D',  'D',  'D'],
[ 'B',  'D',   'A',  'D', 'D']]]
```
**Note**: you don't have to use Numpy in this question.

In [ ]:
# your code here